<?php

namespace AppBundle\Repository;

/**
 * dataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dataRepository extends \Doctrine\ORM\EntityRepository
{
}
